version: '3.7'

services:
  php:
    image: "php:8.2"
    volumes:
      - "./:/app"
    working_dir: "/app"
    environment:
      - "ES_URL=http://elasticsearch:9200"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:8.12.0
    environment:
      - "discovery.type=${ES_DISCOVERY_TYPE:-single-node}"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS:--Xms512m -Xmx512m}"
    ports:
      - "9200:9200"
